In [1]:
import numpy as np
import pandas as pd

In [2]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.2],
               [4, 5,   6.4]])

a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]]])

In [5]:
a2

array([[1. , 2. , 3.2],
       [4. , 5. , 6.4]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
# kształt
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (2, 3, 3))

In [8]:
# wymiary
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [9]:
# typ
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [10]:
# rozmiar
a1.size, a2.size, a3.size

(3, 6, 18)

In [11]:
# rodzaj
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [12]:
# Create a DataFrame (pandas) from NumPy array
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.2
1  4.0  5.0  6.4

In [13]:
ones = np.ones((2, 3))
zeros = np.zeros((2, 3))
ones, zeros

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[0., 0., 0.],
        [0., 0., 0.]]))

In [14]:
# wygenerowanie tablicy jednowymiarowej z wartościami od 0 do 10 z krokiem co 2
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [17]:
# wygenerowanie tablicy dwuwymiarowej z wartościami pseudolosowymi int w zakresie od 0 do 10, o kształcie 3 na 5
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[6, 3, 4, 6, 2],
       [1, 6, 7, 1, 6],
       [8, 4, 5, 6, 6]])

In [19]:
# wygenerowanie tablicy dwuwymiarowej z wartościami pseudolosowymi float w zakresie od 0 do 1, o kształcie 5 na 5
np.random.random((5, 5))

array([[0.77348979, 0.07156598, 0.32266272, 0.98474098, 0.72527703],
       [0.59146086, 0.42867026, 0.64383117, 0.03444094, 0.2354978 ],
       [0.36534206, 0.34681921, 0.48233168, 0.87858739, 0.92875368],
       [0.81919754, 0.92553379, 0.70506455, 0.57726671, 0.1801181 ],
       [0.88120562, 0.86066674, 0.50057407, 0.34500995, 0.38101632]])

In [21]:
# jw. 
random_array_2 = np.random.rand(5, 5) 
random_array_2

array([[0.70130055, 0.53114629, 0.0106299 , 0.42915828, 0.24946261],
       [0.77564083, 0.05785102, 0.88037509, 0.97070985, 0.66461925],
       [0.24397535, 0.44392867, 0.09505635, 0.48829931, 0.16168208],
       [0.34064619, 0.26121802, 0.58471891, 0.42927804, 0.3931692 ],
       [0.64416642, 0.02660273, 0.36360434, 0.52631761, 0.14173869]])

In [22]:
# wygenerowanie tablicy trójwymiarowej random 0-1
random_array_3 = np.random.rand(3, 3, 3)
random_array_3

array([[[0.33049352, 0.90366055, 0.95822835],
        [0.01778242, 0.81944685, 0.39345925],
        [0.71047147, 0.67563004, 0.95217557]],

       [[0.44058864, 0.78017168, 0.19771088],
        [0.1256077 , 0.09309512, 0.5612043 ],
        [0.57607896, 0.40916239, 0.34302252]],

       [[0.41365392, 0.29985901, 0.7395637 ],
        [0.20637439, 0.38670445, 0.33725693],
        [0.01674516, 0.3183131 , 0.60049795]]])

### Random Seed - stały start random

In [24]:
# stały start random
np.random.seed(seed=42) #liczba może być dowolna 
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]])

In [25]:
random_array_5 = np.random.rand(3, 3)
random_array_5

array([[5.64115790e-02, 7.21998772e-01, 9.38552709e-01],
       [7.78765841e-04, 9.92211559e-01, 6.17481510e-01],
       [6.11653160e-01, 7.06630522e-03, 2.30624250e-02]])

In [26]:
# wyświetlenie niepowtarzalnych elementów w tablicy
np.unique(random_array_4) 

array([2, 3, 4, 5, 6, 7, 9])

In [29]:
a1

array([1, 2, 3])

In [30]:
a2

array([[1. , 2. , 3.2],
       [4. , 5. , 6.4]])

In [31]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [34]:
a1[0] # pierwsza pozycja w tablicy jednowymiarowej

1

In [37]:
a2[0] # pierwszy wiersz (wymiar) w tablicy dwuwymiarowej

array([1. , 2. , 3.2])

In [36]:
a3[0] # wyświetlenie pierwszej płaszczyzny (dwuwymiar) w tablicy trójwymiarowej

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
print(a3[:2, :2, :2]) # wyświetl do drugiej kolumny, drugiego wiersza i drugiego poziomu

[[[ 1  2]
  [ 4  5]]

 [[10 11]
  [13 14]]]


In [39]:
a4 = np.random.randint(10, size=(2, 3, 4, 5)) # wymiary po kolei od lewej (4, 3, 2, 1)
a4

array([[[[9, 2, 6, 3, 8],
         [2, 4, 2, 6, 4],
         [8, 6, 1, 3, 8],
         [1, 9, 8, 9, 4]],

        [[1, 3, 6, 7, 2],
         [0, 3, 1, 7, 3],
         [1, 5, 5, 9, 3],
         [5, 1, 9, 1, 9]],

        [[3, 7, 6, 8, 7],
         [4, 1, 4, 7, 9],
         [8, 8, 0, 8, 6],
         [8, 7, 0, 7, 7]]],


       [[[2, 0, 7, 2, 2],
         [0, 4, 9, 6, 9],
         [8, 6, 8, 7, 1],
         [0, 6, 6, 7, 4]],

        [[2, 7, 5, 2, 0],
         [2, 4, 2, 0, 4],
         [9, 6, 6, 8, 9],
         [9, 2, 6, 0, 3]],

        [[3, 4, 6, 6, 3],
         [6, 2, 5, 1, 9],
         [8, 4, 5, 3, 9],
         [6, 8, 6, 0, 0]]]])

In [41]:
a4[:, :, :, :4] # obcięcie pierwszego wymiary czyli x do 4 miejsc

array([[[[9, 2, 6, 3],
         [2, 4, 2, 6],
         [8, 6, 1, 3],
         [1, 9, 8, 9]],

        [[1, 3, 6, 7],
         [0, 3, 1, 7],
         [1, 5, 5, 9],
         [5, 1, 9, 1]],

        [[3, 7, 6, 8],
         [4, 1, 4, 7],
         [8, 8, 0, 8],
         [8, 7, 0, 7]]],


       [[[2, 0, 7, 2],
         [0, 4, 9, 6],
         [8, 6, 8, 7],
         [0, 6, 6, 7]],

        [[2, 7, 5, 2],
         [2, 4, 2, 0],
         [9, 6, 6, 8],
         [9, 2, 6, 0]],

        [[3, 4, 6, 6],
         [6, 2, 5, 1],
         [8, 4, 5, 3],
         [6, 8, 6, 0]]]])

## Manipulate arrays

### dodawanie, odejmowanie

In [42]:
a1

array([1, 2, 3])

In [43]:
a1 + 1 

array([2, 3, 4])

In [45]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [46]:
a1 + ones

array([2., 3., 4.])

In [47]:
a1 - ones

array([0., 1., 2.])

### monożenie, dzielenie przez tablice tego samego wymiaru

In [49]:
a2

array([[1. , 2. , 3.2],
       [4. , 5. , 6.4]])

In [50]:
a1 * a2

array([[ 1. ,  4. ,  9.6],
       [ 4. , 10. , 19.2]])

In [51]:
a1 / ones

array([1., 2., 3.])

In [52]:
a2 / a1

array([[1.        , 1.        , 1.06666667],
       [4.        , 2.5       , 2.13333333]])

In [53]:
a2 // a1 # dzielenie bez reszt (obcinanie do dołu)

array([[1., 1., 1.],
       [4., 2., 2.]])

In [54]:
a2 ** 2 # do potęgi 2

array([[ 1.  ,  4.  , 10.24],
       [16.  , 25.  , 40.96]])

In [58]:
a2 % a1 # reszta z dzielenia

array([[0. , 0. , 0.2],
       [0. , 1. , 0.4]])

### funkcje wbudowane

In [56]:
np.square(a2) # też potęga 2

array([[ 1.  ,  4.  , 10.24],
       [16.  , 25.  , 40.96]])

In [57]:
np.add(a1, a2)

array([[2. , 4. , 6.2],
       [5. , 7. , 9.4]])

In [59]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [60]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

## Aggregation

In [61]:
listy_list = [1, 2, 3]
type(listy_list)

list

In [62]:
# suma elementów tablicy
sum(listy_list)

6

In [63]:
a1

array([1, 2, 3])

In [64]:
sum(a1)

6

In [65]:
np.sum(a1)

6

#### taki sam wynik, ale powinno się używać metod numpy na danych numpy, a metod pythona na danych pythona

## Wielkie tablice

In [75]:
massive_array = np.random.random(10000)
massive_array.size

10000

In [76]:
massive_array[:10]

array([0.83186291, 0.95750551, 0.65856783, 0.64193174, 0.30253867,
       0.78306817, 0.31431523, 0.68293653, 0.76827837, 0.82811961])

In [77]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

928 µs ± 18.2 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
5.66 µs ± 234 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


## NumPy i operacje na tablicach są o wiele szybsze niż na tablicach w gołym pythonie

In [79]:
a2

array([[1. , 2. , 3.2],
       [4. , 5. , 6.4]])

In [78]:
# średnia z elementów tablicy
np.mean(a2)

3.6

In [80]:
# Standard deviation (standardowe odchylenie) to miara rozproszenia danych wokół ich średniej arytmetycznej. Jest to jedna z najczęściej używanych miar w statystyce.
# Standard deviation jest obliczane jako pierwiastek kwadratowy wariancji. 
# Wariancja mierzy, jak bardzo dane różnią się od średniej, a standard deviation dostarcza miary tego rozrzutu w jednostkach oryginalnych danych.
print(np.std(a2)) # standardowe odchylenie

1.8


In [81]:
# Wariancja (Variance) - W statystyce wariancja to miara, która określa, 
# jak bardzo wartości zbioru danych różnią się od średniej arytmetycznej tych wartości. 
# Im większa wariancja, tym większe są różnice między poszczególnymi wartościami a średnią.
print(np.var(a2)) # variance 

3.24


In [ ]:
print(np.sqrt(np.var(a2))) # standardowe odchylenie, obilczenie na piechote