In [1]:
import numpy as np

In [3]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1, 2.0, 3.2],
               [4, 5,   6.4]])

a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]]])

In [7]:
a2

array([[1. , 2. , 3.2],
       [4. , 5. , 6.4]])

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
# kształt
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (2, 3, 3))

In [10]:
# wymiary
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
# typ
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [12]:
# rozmiar
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
# rodzaj
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)