## Strona biblioteki: https://scikit-learn.org
## Dokumentacja/User Guide: https://scikit-learn.org/stable/user_guide.html

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [9]:
# postać prostej na płaszczyźnie Y = w0 + w1*X1, szykamy w0 i w1
X1 = np.array([1, 2, 3, 4, 5, 6])
Y = np.array([3000, 3250, 3500, 3750, 4000, 4250])
print(X1)
print(Y)
m = len(X1)

[1 2 3 4 5 6]
[3000 3250 3500 3750 4000 4250]


In [12]:
X1 = X1.reshape(m, 1) # zmiana kształtu do dopasowania
print(X1)
print(X1.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [13]:
regression = LinearRegression()
regression.fit(X1, Y)

print(regression.intercept_)
print(regression.coef_[0])

2750.0
250.0


In [14]:
# prosta ma równanie Y = 2750 + 250*X1