In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import fetch_california_housing
from sklearn.metrics import accuracy_score

%matplotlib inline

In [2]:
# Nowy start random.
np.random.seed(42)

# Załaowanie danych.
housing = fetch_california_housing() # pobranie danych 
housing_df = pd.DataFrame(housing['data'], columns=housing['feature_names']) # zamiana dict na df
housing_df['target'] = housing['target'] # dodanie kolumny wyjściowej
housing_df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  target  
0        -122.23   4.526  
1        -122.22   3.585  
2        -122.24   3.521  
3        -122.25   3.413  
4        -122.25   3.422  
...          ...     ...  
20635    -121.09   0.781  
20636    -121.21   0.771  
20637    -121.22   0.923  
20638    -121.32   0.847  
20639    -121.24   0.894  

[20640 rows x 9 columns]

In [3]:
# Rozdzielenie danych na wejściowe 'X' i wyjściowe 'y'.
X = housing_df.drop('target', axis=1) # X = heartr_disease oprócz kolumny target (features, features variables, data)
y = housing_df['target'] # y = kolumna target (labels, targets, target variables)

# Rozdzielenie danych na treningowe i testowe.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [4]:
# Stworzenie obiektu clasyfikatora.
model = RandomForestRegressor(n_estimators=100)

# Dopasowanie drzew obiektu do danych. Zbudowanie drzewa decyzyjnego ze zbioru uczącego (X, y). Zbudowanie modelu ML.
model.fit(X_train, y_train) 

# Przetestowanie na modelu danych testowych. Zwraca średnią dokładność dla podanych danych testowych i etykiet.
model.score(X_test, y_test)

0.8051230593157366

## Dwa sposoby na predict
    * 'predict()'
    * 'predict_proba()'

## PREDICT

In [6]:
# Wyniki z modely ML.
y_preds = model.predict(X_test)
y_preds

array([0.5095   , 0.74161  , 4.9232571, ..., 4.7582187, 0.71409  ,
       1.65083  ])

In [7]:
# Wyniki prawdziwe testowe.
np.array(y_test)

array([0.477  , 0.458  , 5.00001, ..., 5.00001, 0.723  , 1.515  ])

In [8]:
# Porównanie wyników.
y_preds == np.array(y_test)

array([False, False, False, ..., False, False, False])

In [9]:
# Średnia porównnia wynmików.
np.mean(y_preds == y_test)

0.0

In [12]:
# Dokładność klasyfikacji.
accuracy_score(y_test, y_preds)

ValueError: continuous is not supported

## PREDICT_PROBA
Oszacowania prawdopodobieństwa. Zwrócone szacunki dla wszystkich klas są uporządkowane według etykiet klas.
Można uzyskać bardziej szczegółowe dane.

In [ ]:
clf.predict_proba(X_test[:5])

In [ ]:
clf.predict(X_test[:5])

predict_proba() pokazuje wagowo w wierszu wynik predict(), np:
- pierwszy wiersz w predict_proba() pokazuje że w 91% będzie 0, co widać na pierwszej popzycji w predict()
- drugi wiersz w predict_proba() pokazuje że w 60% będzie 1, co widać na drugiej popzycji w predict()
- trzeci wiersz w predict_proba() pokazuje że w 53.333% będzie 1, co widać na trzeciej popzycji w predict()
- itd.