In [1]:
import tensorflow as tf
tf.__version__

'2.16.1'

## Stały tensor

In [12]:
# Tworzenie stałego tensora z pojedynczą liczbą - (skalar)
x = tf.constant(5)
x, x.ndim, x.shape

(<tf.Tensor: shape=(), dtype=int32, numpy=5>, 0, TensorShape([]))

In [13]:
# Tworzenie stałego tensora z tablicą NumPy - (wektor)
y = tf.constant([1., 2., 3., 4., 5.])
y, y.ndim, y.shape

(<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 2., 3., 4., 5.], dtype=float32)>,
 1,
 TensorShape([5]))

In [14]:
# Tworzenie stałego tensora o określonym kształcie i typie danych - (matrix)
z = tf.constant([[1, 2], 
                 [3, 4]], dtype=tf.float32) # jeżeli nie podam dtype to wywnioskuje z danych
z, z.ndim, z.shape

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 2.],
        [3., 4.]], dtype=float32)>,
 2,
 TensorShape([2, 2]))

In [19]:
# Rózny kształt
a = tf.constant([[1, 2], 
                 [3, 4],
                 [5, 6]]) # jeżeli nie podam dtype to wywnioskuje z danych
a, a.ndim, a.shape, a.dtype

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 2,
 TensorShape([3, 2]),
 tf.int32)

In [26]:
# Wielowymiarowy
b = tf.constant([[[1, 2, 3],
                  [4, 5, 6]],
                 [[7, 8, 9],
                  [1, 2, 3]],
                 [[3, 2, 1],
                  [4, 1, 0]]])
b, b.ndim

(<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
 array([[[1, 2, 3],
         [4, 5, 6]],
 
        [[7, 8, 9],
         [1, 2, 3]],
 
        [[3, 2, 1],
         [4, 1, 0]]])>,
 3)

## Zmienny tensor

In [36]:
# Porównanie zmiennego do stałego
x = tf.Variable([10, 7])
y = tf.constant([10, 7])

x, y

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [37]:
# Zmana wartości
x[0].assign(2)
x

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 7])>

In [43]:
# Odczyt i zamiana do zwykłej zmiennej
y = x[1].numpy()
y

7

## Random tensor

In [66]:
# Generowanie losowego tensora o kształcie (3, 3) z wartościami z rozkładu normalnego
x = tf.random.Generator.from_seed(42)
x = x.normal(shape=(3, 2))
y = tf.random.Generator.from_seed(42)
y = y.normal(shape=(3, 2))
x, y, x==y

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [77]:
tf.random.set_seed(42)
x = tf.random.normal([2,2])
tf.random.set_seed(42)
y = tf.random.normal([2,2])

x, y, x==y

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 0.3274685, -0.8426258],
        [ 0.3194337, -1.4075519]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 0.3274685, -0.8426258],
        [ 0.3194337, -1.4075519]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True]])>)

In [85]:
x = tf.random.normal(shape=(3, 3)) # rozkład normalny
y = tf.random.uniform(shape=(3, 3)) # zawierającego losowe wartości z rozkładu jednostajnego
z = tf.random.poisson(shape=(3, 3), lam=2) #  losowe wartości z rozkładu Poissona

x, y, z

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.3741168 ,  1.3486496 ,  1.4507792 ],
        [ 0.12905405, -0.36130652,  1.3606943 ],
        [ 0.95027083,  0.7913111 ,  0.05056299]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[0.95171106, 0.12621379, 0.04421461],
        [0.3843361 , 0.970186  , 0.8468393 ],
        [0.11516833, 0.21383655, 0.94459426]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[1., 2., 1.],
        [2., 6., 0.],
        [0., 3., 0.]], dtype=float32)>)