In [1]:
import tensorflow as tf
tf.__version__

'2.16.1'

In [2]:
# Tworzenie stałego tensora z pojedynczą liczbą - (skalar)
x = tf.constant(5)
x

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [3]:
# Tworzenie stałego tensora z tablicą NumPy - (wektor)
y = tf.constant([1, 2, 3, 4, 5])
y

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5])>

In [4]:
# Tworzenie stałego tensora o określonym kształcie i typie danych - (matrix)
z = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
z

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [5]:
# Ilość wymiarów tensorów
x.ndim, y.ndim, z.ndim

(0, 1, 2)