In [1]:
import tensorflow as tf
tf.__version__

'2.16.1'

## Stały tensor

In [2]:
# Tworzenie stałego tensora z pojedynczą liczbą - (skalar)
x = tf.constant(5)
x, x.ndim, x.shape

(<tf.Tensor: shape=(), dtype=int32, numpy=5>, 0, TensorShape([]))

In [3]:
# Tworzenie stałego tensora z tablicą NumPy - (wektor)
y = tf.constant([1., 2., 3., 4., 5.])
y, y.ndim, y.shape

(<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 2., 3., 4., 5.], dtype=float32)>,
 1,
 TensorShape([5]))

In [4]:
# Tworzenie stałego tensora o określonym kształcie i typie danych - (matrix)
z = tf.constant([[1, 2], 
                 [3, 4]], dtype=tf.float32) # jeżeli nie podam dtype to wywnioskuje z danych
z, z.ndim, z.shape

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 2.],
        [3., 4.]], dtype=float32)>,
 2,
 TensorShape([2, 2]))

In [5]:
# Rózny kształt
a = tf.constant([[1, 2], 
                 [3, 4],
                 [5, 6]]) # jeżeli nie podam dtype to wywnioskuje z danych
a, a.ndim, a.shape, a.dtype

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 2,
 TensorShape([3, 2]),
 tf.int32)

In [6]:
# Wielowymiarowy
b = tf.constant([[[1, 2, 3],
                  [4, 5, 6]],
                 [[7, 8, 9],
                  [1, 2, 3]],
                 [[3, 2, 1],
                  [4, 1, 0]]])
b, b.ndim

(<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
 array([[[1, 2, 3],
         [4, 5, 6]],
 
        [[7, 8, 9],
         [1, 2, 3]],
 
        [[3, 2, 1],
         [4, 1, 0]]])>,
 3)

## Zmienny tensor

In [7]:
# Porównanie zmiennego do stałego
x = tf.Variable([10, 7])
y = tf.constant([10, 7])

x, y

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [8]:
# Zmana wartości
x[0].assign(2)
x

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 7])>

In [9]:
# Odczyt i zamiana do zwykłej zmiennej
y = x[1].numpy()
y

7

## Random tensor

In [10]:
# Generowanie losowego tensora o kształcie (3, 3) z wartościami z rozkładu normalnego
x = tf.random.Generator.from_seed(42)
x = x.normal(shape=(3, 2))
y = tf.random.Generator.from_seed(42)
y = y.normal(shape=(3, 2))
x, y, x==y

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [39]:
tf.random.set_seed(42)
x = tf.random.normal([2,2])
tf.random.set_seed(42)
y = tf.random.normal([2,2])

x, y, x==y

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 0.3274685, -0.8426258],
        [ 0.3194337, -1.4075519]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 0.3274685, -0.8426258],
        [ 0.3194337, -1.4075519]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True]])>)

In [38]:
x = tf.random.normal(shape=(3, 3)) # rozkład normalny
y = tf.random.uniform(shape=(3, 3)) # zawierającego losowe wartości z rozkładu jednostajnego
z = tf.random.poisson(shape=(3, 3), lam=2) #  losowe wartości z rozkładu Poissona

x, y, z

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.3274685, -0.8426258,  0.3194337],
        [-1.4075519, -2.3880599, -1.0392479],
        [-0.5573232,  0.539707 ,  1.6994323]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[0.68789124, 0.48447883, 0.9309944 ],
        [0.252187  , 0.73115396, 0.89256823],
        [0.94674826, 0.7493341 , 0.34925628]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[1., 2., 4.],
        [1., 1., 6.],
        [3., 4., 1.]], dtype=float32)>)

## Tasowanie danymi w tensorze

In [42]:
# tasuje dane tylko elementami najwyższego wymiaru
tf.random.set_seed(42)
data = tf.constant([[1, 2], [3, 4], [5, 6], [7, 8]])
tf.random.shuffle(data)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[7, 8],
       [1, 2],
       [3, 4],
       [5, 6]])>

## Seed globalny i operacyjny

In [47]:
# Globalny seed: 
# Ustawienie globalnego ziarna (global seed) umożliwia ustalenie ziarna generatora liczb pseudolosowych dla całej sesji TensorFlow. 
# Możesz to zrobić przy użyciu tf.random.set_seed(). Ustawienie globalnego ziarna pozwala na kontrolowanie losowości w całej sesji TensorFlow. 
# Na przykład:
# Ustawienie globalnego ziarna
tf.random.set_seed(123)
# Tworzenie tensora z losowymi wartościami
tf.random.normal(shape=(3, 3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.8980837 , -1.8259144 , -0.44441807],
       [-1.4882947 , -0.7855463 ,  0.19619656],
       [ 0.17604655, -1.5252506 ,  0.635294  ]], dtype=float32)>

In [51]:
# Seed operacyjny: 
# Możesz również ustawić ziarno (seed) dla konkretnej operacji lub tensora, co umożliwia kontrolę nad losowością dla danej operacji lub tensora. 
# Możesz to zrobić poprzez ustawienie parametru seed w odpowiedniej funkcji TensorFlow, na przykład tf.random.shuffle().
# Ustawienie seed operacyjnego dla tasowania danych
tf.random.shuffle(data, seed=123)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[7, 8],
       [3, 4],
       [1, 2],
       [5, 6]])>

In [68]:
tf.random.set_seed(123)
x = tf.random.normal(shape=(3, 3))
y = tf.random.normal(shape=(3, 3), seed=12) # zmieniając wartość seed operacyjną, zmieniamy losowanie, tylko dla tej operacji
z = tf.random.normal(shape=(3, 3))
x, y, z

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-0.8980837 , -1.8259144 , -0.44441807],
        [-1.4882947 , -0.7855463 ,  0.19619656],
        [ 0.17604655, -1.5252506 ,  0.635294  ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.9301948 ,  0.09106961,  0.3893619 ],
        [ 1.4705666 ,  0.3001138 , -0.8969683 ],
        [ 0.42988804,  1.3693097 ,  0.79081714]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.33875433,  0.3449861 , -0.6605785 ],
        [-0.2854994 ,  0.43852386,  0.8288566 ],
        [-0.53591555, -0.5353483 , -1.0324248 ]], dtype=float32)>)