In [1]:
import tensorflow as tf
tf.__version__

'2.16.1'

## Stały tensor

In [12]:
# Tworzenie stałego tensora z pojedynczą liczbą - (skalar)
x = tf.constant(5)
x, x.ndim, x.shape

(<tf.Tensor: shape=(), dtype=int32, numpy=5>, 0, TensorShape([]))

In [13]:
# Tworzenie stałego tensora z tablicą NumPy - (wektor)
y = tf.constant([1., 2., 3., 4., 5.])
y, y.ndim, y.shape

(<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 2., 3., 4., 5.], dtype=float32)>,
 1,
 TensorShape([5]))

In [14]:
# Tworzenie stałego tensora o określonym kształcie i typie danych - (matrix)
z = tf.constant([[1, 2], 
                 [3, 4]], dtype=tf.float32) # jeżeli nie podam dtype to wywnioskuje z danych
z, z.ndim, z.shape

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 2.],
        [3., 4.]], dtype=float32)>,
 2,
 TensorShape([2, 2]))

In [19]:
# Rózny kształt
a = tf.constant([[1, 2], 
                 [3, 4],
                 [5, 6]]) # jeżeli nie podam dtype to wywnioskuje z danych
a, a.ndim, a.shape, a.dtype

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 2,
 TensorShape([3, 2]),
 tf.int32)

In [26]:
# Wielowymiarowy
b = tf.constant([[[1, 2, 3],
                  [4, 5, 6]],
                 [[7, 8, 9],
                  [1, 2, 3]],
                 [[3, 2, 1],
                  [4, 1, 0]]])
b, b.ndim

(<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
 array([[[1, 2, 3],
         [4, 5, 6]],
 
        [[7, 8, 9],
         [1, 2, 3]],
 
        [[3, 2, 1],
         [4, 1, 0]]])>,
 3)

## Zmienny tensor

In [36]:
# Porównanie zmiennego do stałego
x = tf.Variable([10, 7])
y = tf.constant([10, 7])

x, y

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [37]:
# Zmana wartości
x[0].assign(2)
x

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 7])>

In [43]:
# Odczyt i zamiana do zwykłej zmiennej
y = x[1].numpy()
y

7

## Random tensor