In [1]:
import tensorflow as tf
print(tf.__version__)
import numpy as np

2.16.1


## Stały tensor

In [2]:
# Tworzenie stałego tensora z pojedynczą liczbą - (skalar)
x = tf.constant(5)
x, x.ndim, x.shape

(<tf.Tensor: shape=(), dtype=int32, numpy=5>, 0, TensorShape([]))

In [3]:
# Tworzenie stałego tensora z tablicą NumPy - (wektor)
y = tf.constant([1., 2., 3., 4., 5.])
y, y.ndim, y.shape

(<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 2., 3., 4., 5.], dtype=float32)>,
 1,
 TensorShape([5]))

In [4]:
# Tworzenie stałego tensora o określonym kształcie i typie danych - (matrix)
z = tf.constant([[1, 2], 
                 [3, 4]], dtype=tf.float32) # jeżeli nie podam dtype to wywnioskuje z danych
z, z.ndim, z.shape

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 2.],
        [3., 4.]], dtype=float32)>,
 2,
 TensorShape([2, 2]))

In [5]:
# Rózny kształt
a = tf.constant([[1, 2], 
                 [3, 4],
                 [5, 6]]) # jeżeli nie podam dtype to wywnioskuje z danych
a, a.ndim, a.shape, a.dtype

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 2,
 TensorShape([3, 2]),
 tf.int32)

In [6]:
# Wielowymiarowy
b = tf.constant([[[1, 2, 3],
                  [4, 5, 6]],
                 [[7, 8, 9],
                  [1, 2, 3]],
                 [[3, 2, 1],
                  [4, 1, 0]]])
b, b.ndim

(<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
 array([[[1, 2, 3],
         [4, 5, 6]],
 
        [[7, 8, 9],
         [1, 2, 3]],
 
        [[3, 2, 1],
         [4, 1, 0]]])>,
 3)

## Zmienny tensor

In [7]:
# Porównanie zmiennego do stałego
x = tf.Variable([10, 7])
y = tf.constant([10, 7])

x, y

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [8]:
# Zmana wartości
x[0].assign(2)
x

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 7])>

In [9]:
# Odczyt i zamiana do zwykłej zmiennej
y = x[1].numpy()
y

7

## Random tensor

In [10]:
# Generowanie losowego tensora o kształcie (3, 3) z wartościami z rozkładu normalnego
x = tf.random.Generator.from_seed(42)
x = x.normal(shape=(3, 2))
y = tf.random.Generator.from_seed(42)
y = y.normal(shape=(3, 2))
x, y, x==y

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [11]:
tf.random.set_seed(42)
x = tf.random.normal([2,2])
tf.random.set_seed(42)
y = tf.random.normal([2,2])

x, y, x==y

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 0.3274685, -0.8426258],
        [ 0.3194337, -1.4075519]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 0.3274685, -0.8426258],
        [ 0.3194337, -1.4075519]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True]])>)

In [12]:
x = tf.random.normal(shape=(3, 3)) # rozkład normalny
y = tf.random.uniform(shape=(3, 3)) # zawierającego losowe wartości z rozkładu jednostajnego
z = tf.random.poisson(shape=(3, 3), lam=2) #  losowe wartości z rozkładu Poissona

x, y, z

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.08422458, -0.86090374,  0.37812304],
        [-0.00519627, -0.49453196,  0.6178192 ],
        [-0.33082047, -0.00138408, -0.4237341 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[0.7413678 , 0.62854624, 0.01738465],
        [0.3431449 , 0.51063764, 0.3777541 ],
        [0.07321596, 0.02137029, 0.2871771 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[2., 1., 1.],
        [4., 1., 1.],
        [3., 0., 2.]], dtype=float32)>)

## Tasowanie danymi w tensorze

In [13]:
# tasuje dane tylko elementami najwyższego wymiaru
tf.random.set_seed(42)
data = tf.constant([[1, 2], [3, 4], [5, 6], [7, 8]])
tf.random.shuffle(data)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[7, 8],
       [1, 2],
       [3, 4],
       [5, 6]])>

## Seed globalny i operacyjny

In [14]:
# Globalny seed: 
# Ustawienie globalnego ziarna (global seed) umożliwia ustalenie ziarna generatora liczb pseudolosowych dla całej sesji TensorFlow. 
# Możesz to zrobić przy użyciu tf.random.set_seed(). Ustawienie globalnego ziarna pozwala na kontrolowanie losowości w całej sesji TensorFlow. 
# Na przykład:
# Ustawienie globalnego ziarna
tf.random.set_seed(123)
# Tworzenie tensora z losowymi wartościami
tf.random.normal(shape=(3, 3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.8980837 , -1.8259144 , -0.44441807],
       [-1.4882947 , -0.7855463 ,  0.19619656],
       [ 0.17604655, -1.5252506 ,  0.635294  ]], dtype=float32)>

In [15]:
# Seed operacyjny: 
# Możesz również ustawić ziarno (seed) dla konkretnej operacji lub tensora, co umożliwia kontrolę nad losowością dla danej operacji lub tensora. 
# Możesz to zrobić poprzez ustawienie parametru seed w odpowiedniej funkcji TensorFlow, na przykład tf.random.shuffle().
# Ustawienie seed operacyjnego dla tasowania danych
tf.random.shuffle(data, seed=123)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[7, 8],
       [1, 2],
       [5, 6],
       [3, 4]])>

In [16]:
tf.random.set_seed(123)
x = tf.random.normal(shape=(3, 3))
y = tf.random.normal(shape=(3, 3), seed=12) # zmieniając wartość seed operacyjną, zmieniamy losowanie, tylko dla tej operacji
z = tf.random.normal(shape=(3, 3))
x, y, z

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-0.8980837 , -1.8259144 , -0.44441807],
        [-1.4882947 , -0.7855463 ,  0.19619656],
        [ 0.17604655, -1.5252506 ,  0.635294  ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.9301948 ,  0.09106961,  0.3893619 ],
        [ 1.4705666 ,  0.3001138 , -0.8969683 ],
        [ 0.42988804,  1.3693097 ,  0.79081714]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.33875433,  0.3449861 , -0.6605785 ],
        [-0.2854994 ,  0.43852386,  0.8288566 ],
        [-0.53591555, -0.5353483 , -1.0324248 ]], dtype=float32)>)

## Inne sposoby tworzenia tensorów

In [17]:
tf.ones(shape=(2, 3), dtype=tf.int32)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]])>

In [18]:
tf.zeros(shape=(1,2))

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0., 0.]], dtype=float32)>

In [19]:
x = np.zeros([2, 3])
y = np.ones([3, 4])
x, y

(array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]))

In [20]:
# z numpy na tensor
tx = tf.constant(x, dtype=tf.int64) # odrazu rzutowanie na typ int64, bo z automatu numpy zrobiło float
tx

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int64)>

In [21]:
# z numpy na tensor ze zmianą kształtu
tx = tf.constant(x, shape=(6))
ty = tf.constant(x, shape=(3, 2))
tx, ty

(<tf.Tensor: shape=(6,), dtype=float64, numpy=array([0., 0., 0., 0., 0., 0.])>,
 <tf.Tensor: shape=(3, 2), dtype=float64, numpy=
 array([[0., 0.],
        [0., 0.],
        [0., 0.]])>)

## Atrybuty tensora
* shape
* rank 
* axis or dimension 
* size 

In [22]:
tf.random.set_seed(42)
rank_4_tensor = tf.random.normal(shape=(2, 3, 4, 5), dtype=tf.float16)
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float16, numpy=
array([[[[ 3.2739e-01, -8.4277e-01,  3.1934e-01, -1.4072e+00,
          -2.3887e+00],
         [-1.0391e+00, -5.5713e-01,  5.3955e-01,  1.6992e+00,
           2.8882e-01],
         [-1.5068e+00, -2.6465e-01, -5.9717e-01, -1.9170e+00,
          -6.2061e-01],
         [ 8.5059e-01, -4.0601e-01, -3.0254e+00,  9.0576e-01,
           2.9858e-01]],

        [[-2.2559e-01, -7.6172e-01, -1.8916e+00, -9.3848e-01,
           7.7832e-01],
         [-4.7339e-01,  9.7754e-01,  2.4695e-01,  2.0569e-01,
          -5.2539e-01],
         [ 3.2422e-01,  2.5452e-02, -1.0638e-01, -6.3672e-01,
           1.1602e+00],
         [ 2.5073e-01, -4.1724e-01,  4.0137e-01, -1.4141e+00,
          -5.9326e-01]],

        [[-1.6621e+00,  3.3569e-01,  1.0815e-01,  2.3474e-01,
          -5.6689e-01],
         [-3.5815e-01,  8.8721e-01,  5.2734e-01,  7.0410e-01,
          -3.3423e-01],
         [ 2.1643e-01, -9.7510e-01, -2.0752e-01, -3.6469e-02,
          -1.3350e+0

In [23]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float16, numpy=
array([[[ 0.3274 , -0.843  ,  0.3193 , -1.407  , -2.389  ],
        [-1.039  , -0.557  ,  0.5396 ,  1.699  ,  0.2888 ],
        [-1.507  , -0.2646 , -0.597  , -1.917  , -0.6206 ],
        [ 0.8506 , -0.406  , -3.025  ,  0.906  ,  0.2986 ]],

       [[-0.2256 , -0.7617 , -1.892  , -0.9385 ,  0.7783 ],
        [-0.4734 ,  0.9775 ,  0.247  ,  0.2057 , -0.5254 ],
        [ 0.3242 ,  0.02545, -0.1064 , -0.6367 ,  1.16   ],
        [ 0.2507 , -0.4172 ,  0.4014 , -1.414  , -0.5933 ]],

       [[-1.662  ,  0.3357 ,  0.10815,  0.2347 , -0.567  ],
        [-0.3582 ,  0.887  ,  0.5273 ,  0.704  , -0.3342 ],
        [ 0.2164 , -0.975  , -0.2075 , -0.03647, -1.335  ],
        [ 0.6885 ,  1.111  ,  0.4014 ,  0.632  , -0.3904 ]]],
      dtype=float16)>

In [24]:
rank_4_tensor[0, 0]

<tf.Tensor: shape=(4, 5), dtype=float16, numpy=
array([[ 0.3274, -0.843 ,  0.3193, -1.407 , -2.389 ],
       [-1.039 , -0.557 ,  0.5396,  1.699 ,  0.2888],
       [-1.507 , -0.2646, -0.597 , -1.917 , -0.6206],
       [ 0.8506, -0.406 , -3.025 ,  0.906 ,  0.2986]], dtype=float16)>

In [25]:
rank_4_tensor[0, 0, 0]

<tf.Tensor: shape=(5,), dtype=float16, numpy=array([ 0.3274, -0.843 ,  0.3193, -1.407 , -2.389 ], dtype=float16)>

In [26]:
rank_4_tensor[0, 0, 0, 0]

<tf.Tensor: shape=(), dtype=float16, numpy=0.3274>

In [27]:
out = list(rank_4_tensor.shape)
out

[2, 3, 4, 5]

In [28]:
out = (rank_4_tensor.shape[0]) # pierwszy
out

2

In [29]:
out = (rank_4_tensor.shape[-1]) # ostatni
out

5

In [30]:
out = rank_4_tensor.ndim
out

4

In [31]:
out = tf.size(rank_4_tensor).numpy()
out

120

## Indeksowanie w tensorach

In [32]:
# Ineksowanie w tensorach jest takie samo jak w listach python
lista = [1, 2, 3, 4, 5, 6, 7] 
lista[:2] # pierwsze dwa elementy

[1, 2]

In [33]:
tensor = tf.constant([[[1, 2],
                       [3, 4]],
                      [[5, 6],
                       [7, 8]],
                      [[9, 0],
                       [1, 2]]])
tensor, tensor.ndim

(<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
 array([[[1, 2],
         [3, 4]],
 
        [[5, 6],
         [7, 8]],
 
        [[9, 0],
         [1, 2]]])>,
 3)

In [34]:
tensor[:1]

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]])>

## Rozszerzenie tensora

In [35]:
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [36]:
# każdy ostatni element wiersza
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4])>

In [37]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [39]:
# Przykładowy jednowymiarowy tensor
tensor = tf.constant([1, 2, 3, 4, 5])
# Dodanie nowej osi do tensora
new_tensor = tensor[..., tf.newaxis]
# Wyświetlenie nowego tensora
print(new_tensor)

tf.Tensor(
[[1]
 [2]
 [3]
 [4]
 [5]], shape=(5, 1), dtype=int32)


In [41]:
# Opcja alternatywna dla poszerzenia wymiaru
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [47]:
tensor = tf.constant([[[1, 2],
                       [2, 3]],
                      [[3, 4],
                       [4, 5]],
                      [[5, 6],
                       [6, 7]]])
tensor

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [2, 3]],

       [[3, 4],
        [4, 5]],

       [[5, 6],
        [6, 7]]])>

In [48]:
tensor[..., tf.newaxis]

<tf.Tensor: shape=(3, 2, 2, 1), dtype=int32, numpy=
array([[[[1],
         [2]],

        [[2],
         [3]]],


       [[[3],
         [4]],

        [[4],
         [5]]],


       [[[5],
         [6]],

        [[6],
         [7]]]])>

In [54]:
tf.expand_dims(tensor, axis=0) # dodanie wymiaru z możliwością wyboru 

<tf.Tensor: shape=(1, 3, 2, 2), dtype=int32, numpy=
array([[[[1, 2],
         [2, 3]],

        [[3, 4],
         [4, 5]],

        [[5, 6],
         [6, 7]]]])>

In [55]:
tf.expand_dims(tensor, axis=1)

<tf.Tensor: shape=(3, 1, 2, 2), dtype=int32, numpy=
array([[[[1, 2],
         [2, 3]]],


       [[[3, 4],
         [4, 5]]],


       [[[5, 6],
         [6, 7]]]])>

## Podstawowe operacje na tensorach ('+', '-', '*', '/')

In [57]:
tensor = tf.constant([[1, 2], [3, 4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [58]:
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]])>

In [59]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-9, -8],
       [-7, -6]])>

In [60]:
tensor * 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [6, 8]])>

In [61]:
tensor / 5

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.2, 0.4],
       [0.6, 0.8]])>

In [66]:
# Funkcje wbudowane, tefunkcjie są wspierane przez gpu, a zwykłe operatrory nie muszą być
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]])>

In [63]:
tf.divide(tensor, 2)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.5, 1. ],
       [1.5, 2. ]])>

In [64]:
tf.subtract(tensor, 2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-1,  0],
       [ 1,  2]])>

In [65]:
tf.add(tensor, 46)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[47, 48],
       [49, 50]])>

## Operacje na macierzach (mnożenie macierzy)

In [67]:
print(tensor)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [80]:
# mnożenie 'dot product', liczba kolumn pierwszej macierzy musi być równa liczbie wierszy drugiej macierzy
print(tensor @ tensor)
# lub
print(tf.matmul(tensor, tensor))

tf.Tensor(
[[ 7 10]
 [15 22]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 7 10]
 [15 22]], shape=(2, 2), dtype=int32)


In [81]:
# mnożenie 'element-wise' lub 'mnożenie Hadamarda' -> element przez element, macierze muszą mieć ten sam kształt
print(tensor * tensor)
# lub
print(tf.multiply(tensor, tensor))

tf.Tensor(
[[ 1  4]
 [ 9 16]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 1  4]
 [ 9 16]], shape=(2, 2), dtype=int32)


### DOT PRODUCT

In [96]:
# Zasady monorzenia macierzy metodą dot produkt:
# 1. Wewnętrzne wymiary muszą być takie same:
#    * 3x2 i 2x3,  4x16 i 16x4, 3x3 i 3x2 (2x3 i 2x3 to błąd)
# 2. Wynikiem mnożenia jes macierz o kształcie zewnętrznych wymiarów:
#    * 3x2*2x3=3x3, 3x3*3x2=3x2

In [83]:
tensor1 = tf.constant([[1, 2, 3], [4, 5, 6]])
tensor2 = tf.constant([[1, 2], [3, 4], [5, 6]])
tensor1, tensor2

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>)

In [84]:
print(tf.matmul(tensor1, tensor2))

tf.Tensor(
[[22 28]
 [49 64]], shape=(2, 2), dtype=int32)


### Zmiana kształtu macierzy jak by nie pasiowała do mnorzenia

In [94]:
# zmiana kształtu z przesunięciem elementów
print(tensor2)
print(tf.reshape(tensor2, shape=(2, 3)))

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [95]:
# zmiana kształtu przez obrót
print(tensor2)
print(tf.transpose(tensor2))

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1 3 5]
 [2 4 6]], shape=(2, 3), dtype=int32)
