In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# Nowy start random.
np.random.seed(42)

# Załaowanie danych.
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing() # pobranie danych 
housing_df = pd.DataFrame(housing['data'], columns=housing['feature_names']) # zamiana dict na df
housing_df['target'] = housing['target'] # dodanie kolumny wyjściowej
housing_df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  target  
0        -122.23   4.526  
1        -122.22   3.585  
2        -122.24   3.521  
3        -122.25   3.413  
4        -122.25   3.422  
...          ...     ...  
20635    -121.09   0.781  
20636    -121.21   0.771  
20637    -121.22   0.923  
20638    -121.32   0.847  
20639    -121.24   0.894  

[20640 rows x 9 columns]

In [3]:
# Rozdzielenie danych na wejściowe 'X' i wyjściowe 'y'.
X = housing_df.drop('target', axis=1) # X = heartr_disease oprócz kolumny target (features, features variables, data)
y = housing_df['target'] # y = kolumna target (labels, targets, target variables)

# Rozdzielenie danych na treningowe i testowe.
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [4]:
# Stworzenie obiektu clasyfikatora.
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators=100)

# Dopasowanie drzew obiektu do danych. Zbudowanie drzewa decyzyjnego ze zbioru uczącego (X, y). Zbudowanie modelu ML.
model.fit(X_train, y_train) 

# Przetestowanie na modelu danych testowych. Zwraca średnią dokładność dla podanych danych testowych i etykiet.
model.score(X_test, y_test)

0.8051230593157366

## PREDICT

In [5]:
# Wyniki z modely ML.
y_preds = model.predict(X_test)
y_preds

array([0.5095   , 0.74161  , 4.9232571, ..., 4.7582187, 0.71409  ,
       1.65083  ])

In [6]:
# Wyniki prawdziwe testowe.
np.array(y_test)

array([0.477  , 0.458  , 5.00001, ..., 5.00001, 0.723  , 1.515  ])

In [7]:
# Średni błąd bezwzględny straty regresji.
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_preds)

0.32754256845930246

## Ocena modelu uczenia maszynowego:
1. Wbudowana w estymator metoda "score()".
2. Parametr "scoring".
3. Funkcja metryczna specyficzna dla problemu.
   
https://scikit-learn.org/stable/modules/model_evaluation.html

### Wbudowana w estymator metoda "score()".

In [8]:
# Nowy start random.
np.random.seed(42)
# Załaowanie danych.
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing() # pobranie danych 
housing_df = pd.DataFrame(housing['data'], columns=housing['feature_names']) # zamiana dict na df
housing_df['target'] = housing['target'] # dodanie kolumny wyjściowej
# Rozdzielenie danych na wejściowe 'X' i wyjściowe 'y'.
X = housing_df.drop('target', axis=1) # X = heartr_disease oprócz kolumny target (features, features variables, data)
y = housing_df['target'] # y = kolumna target (labels, targets, target variables)
# Rozdzielenie danych na treningowe i testowe.
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# Stworzenie obiektu clasyfikatora.
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators=100)
# Dopasowanie drzew obiektu do danych. Zbudowanie drzewa decyzyjnego ze zbioru uczącego (X, y). Zbudowanie modelu ML.
model.fit(X_train, y_train) 

RandomForestRegressor()

In [9]:
# Przetestowanie na modelu danych treningowych.
model.score(X_train, y_train)

0.9735726320302575

In [10]:
# Przetestowanie na modelu danych testowych. Zwraca średnią dokładność dla podanych danych testowych i etykiet.
model.score(X_test, y_test)

0.8051230593157366

## math:`R^2` (coefficient of determination) regression score function

R^2 (pronounced r-squared) or the coefficient of determination - Compares your model's predictions to the mean of the targets. Values can range from negative infinity (a very poor model) to 1. For example, if all your model does is predict the mean of the targets, its R^2 value would be 0. And if your model perfectly predicts a range of numbers it's R^2 value would be 1.

R^2 (wymawiane r-kwadrat) lub współczynnik determinacji - porównuje przewidywania modelu ze średnią celów. Wartości mogą wahać się od ujemnej nieskończoności (bardzo słaby model) do 1. Na przykład, jeśli wszystko, co robi model, to przewidywanie średniej celów, jego wartość R^2 wyniesie 0. A jeśli model doskonale przewiduje zakres liczb, jego wartość R^2 wyniesie 1.

In [11]:
y_test

20046    0.47700
3024     0.45800
15663    5.00001
20484    2.18600
9814     2.78000
          ...   
15362    2.63300
16623    2.66800
18086    5.00001
2144     0.72300
3665     1.51500
Name: target, Length: 4128, dtype: float64

In [12]:
y_test.mean()

2.0550030959302323

In [13]:
from sklearn.metrics import r2_score
y_test_mean = np.full(len(y_test), y_test.mean())
y_test_mean

array([2.0550031, 2.0550031, 2.0550031, ..., 2.0550031, 2.0550031,
       2.0550031])

In [14]:
r2_score(y_true=y_test, y_pred=y_test_mean)

0.0

In [15]:
r2_score(y_true=y_test, y_pred=y_preds) # to samo co model.score(X_test, y_test)

0.8051230593157366

## Mean absolute error regression loss.

Mean absolute error (MAE) - The average of the absolute differences between predictions and actual values. It gives you an idea of how wrong your predictions were.

Średni błąd bezwzględny (MAE) - średnia bezwzględnych różnic między przewidywaniami a rzeczywistymi wartościami. Daje wyobrażenie o tym, jak błędne były przewidywania.

In [16]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_true=y_test, y_pred=y_preds) 
mae

0.32754256845930246

In [17]:
df = pd.DataFrame(data={'actual vcalues':y_test, 'predicted values':y_preds})
df['differences'] = df['predicted values'] - df['actual vcalues']
df

actual vcalues  predicted values  differences
20046         0.47700          0.509500     0.032500
3024          0.45800          0.741610     0.283610
15663         5.00001          4.923257    -0.076753
20484         2.18600          2.529610     0.343610
9814          2.78000          2.273690    -0.506310
...               ...               ...          ...
15362         2.63300          2.267210    -0.365790
16623         2.66800          1.993650    -0.674350
18086         5.00001          4.758219    -0.241791
2144          0.72300          0.714090    -0.008910
3665          1.51500          1.650830     0.135830

[4128 rows x 3 columns]

In [18]:
np.abs(df['differences']).mean() # wzór na mean_absolute_error

0.32754256845930246

## Mean squared error regression loss.

Mean squared error (MSE) - The average squared differences between predictions and actual values. Squaring the errors removes negative errors. It also amplifies outliers (samples which have larger errors).

Błąd średniokwadratowy (MSE) - średnia kwadratowa różnica między przewidywaniami a rzeczywistymi wartościami. Kwadratowanie błędów usuwa błędy ujemne. Wzmacnia również wartości odstające (próbki, które mają większe błędy).

In [19]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_true=y_test, y_pred=y_preds) 
mse

0.2553684927247781

In [20]:
df['squared_differences'] = np.square(df['differences'])
df

actual vcalues  predicted values  differences  squared_differences
20046         0.47700          0.509500     0.032500             0.001056
3024          0.45800          0.741610     0.283610             0.080435
15663         5.00001          4.923257    -0.076753             0.005891
20484         2.18600          2.529610     0.343610             0.118068
9814          2.78000          2.273690    -0.506310             0.256350
...               ...               ...          ...                  ...
15362         2.63300          2.267210    -0.365790             0.133802
16623         2.66800          1.993650    -0.674350             0.454748
18086         5.00001          4.758219    -0.241791             0.058463
2144          0.72300          0.714090    -0.008910             0.000079
3665          1.51500          1.650830     0.135830             0.018450

[4128 rows x 4 columns]

In [21]:
df['squared_differences'].mean() # mean_squared_error

0.2553684927247781

# Od nowa

In [22]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestRegressor

In [23]:
np.random.seed(42)
X = housing_df.drop('target', axis=1) 
y = housing_df['target'] 
model = RandomForestRegressor(n_estimators=100)

In [ ]:
np.random.seed(42)
cv_r2 = cross_val_score(model, X, y, cv=3, scoring=None)
np.mean(cv_r2)

In [ ]:
cv_r2

In [ ]:
np.random.seed(42)
cv_mse = cross_val_score(model, X, y, cv=3, scoring='neg_mean_squared_error')
np.mean(cv_mse)

In [ ]:
cv_mse

In [ ]:
np.random.seed(42)
cv_mae = cross_val_score(model, X, y, cv=3, scoring='neg_mean_absolute_error')
np.mean(cv_mae)

In [ ]:
cv_mae