* Strona biblioteki: https://scikit-learn.org
* Dokumentacja/User Guide: https://scikit-learn.org/stable/user_guide.html¶

In [1]:
import numpy as np
import pandas as pd
import sklearn

sklearn.__version__

'1.7.1'

In [2]:
data = {
    "size": ["XL", "L", "M", np.nan, "M", "M"],
    "color": ["red", "green", "blue", "green", "red", "green"],
    "gender": ["female", "male", np.nan, "female", "female", "male"],
    "price": [199.0, 89.0, np.nan, 129.0, 79.0, 89.0],
    "weight": [500, 450, 300, np.nan, 410, np.nan],
    "bought": ["yes", "no", "yes", "no", "yes", "no"],
}

df_raw = pd.DataFrame(data=data)
df_raw

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue     NaN    NaN   300.0    yes
3  NaN  green  female  129.0     NaN     no
4    M    red  female   79.0   410.0    yes
5    M  green    male   89.0     NaN     no

In [3]:
df = df_raw.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   size    5 non-null      object 
 1   color   6 non-null      object 
 2   gender  5 non-null      object 
 3   price   5 non-null      float64
 4   weight  4 non-null      float64
 5   bought  6 non-null      object 
dtypes: float64(2), object(4)
memory usage: 420.0+ bytes


In [4]:
df.isnull()  # maska logiczna z brakami danych

size  color  gender  price  weight  bought
0  False  False   False  False   False   False
1  False  False   False  False   False   False
2  False  False    True   True   False   False
3   True  False   False  False    True   False
4  False  False   False  False   False   False
5  False  False   False  False    True   False

In [5]:
df.isnull().sum()  # liczba pól w kolumnie z brakami danych

size      1
color     0
gender    1
price     1
weight    2
bought    0
dtype: int64

In [6]:
df.isnull().sum().sum()  # łaczna liczba braków danych w ramce

np.int64(5)

In [8]:
df.isnull().sum() / len(df) # jdnostkowy brak danych 

size      0.166667
color     0.000000
gender    0.166667
price     0.166667
weight    0.333333
bought    0.000000
dtype: float64

In [10]:
df.isnull().sum() / len(df) * 100 # procentowy brak danych

size      16.666667
color      0.000000
gender    16.666667
price     16.666667
weight    33.333333
bought     0.000000
dtype: float64

### Uzupełnianie braków
### SimpleImputer

In [12]:
from sklearn.impute import SimpleImputer

In [13]:
df[['weight']]

weight
0   500.0
1   450.0
2   300.0
3     NaN
4   410.0
5     NaN

In [16]:
# rodzaje strategii: mean, median, most_frequent, constant
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(df[['weight']])

SimpleImputer()

In [17]:
imputer.statistics_ # wartość wyliczona 

array([415.])

In [19]:
imputer.transform(df[['weight']]) # uzupełnienie braków w całej kolumnie

array([[500.],
       [450.],
       [300.],
       [415.],
       [410.],
       [415.]])

In [20]:
df['weight'] = imputer.transform(df[['weight']]) 
df

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue     NaN    NaN   300.0    yes
3  NaN  green  female  129.0   415.0     no
4    M    red  female   79.0   410.0    yes
5    M  green    male   89.0   415.0     no

In [26]:
imputer = SimpleImputer(missing_values=np.nan, strategy='constant', fill_value=99.0)  # uzupełnienie stałą wartością 99.0
imputer.fit_transform(df[['price']])

array([[199.],
       [ 89.],
       [ 99.],
       [129.],
       [ 79.],
       [ 89.]])

In [27]:
imputer = SimpleImputer(missing_values=np.nan, strategy='constant', fill_value='L')  # uzupełnienie stałą wartością 99.0
imputer.fit_transform(df[['size']])

array([['XL'],
       ['L'],
       ['M'],
       ['L'],
       ['M'],
       ['M']], dtype=object)

In [28]:
df

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue     NaN    NaN   300.0    yes
3  NaN  green  female  129.0   415.0     no
4    M    red  female   79.0   410.0    yes
5    M  green    male   89.0   415.0     no

In [29]:
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent', fill_value='L')  # uzupełnienie najczęście występującym
imputer.fit_transform(df[['size']])

array([['XL'],
       ['L'],
       ['M'],
       ['M'],
       ['M'],
       ['M']], dtype=object)

In [30]:
df = df_raw.copy()
df

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue     NaN    NaN   300.0    yes
3  NaN  green  female  129.0     NaN     no
4    M    red  female   79.0   410.0    yes
5    M  green    male   89.0     NaN     no

In [32]:
df[pd.isnull(df['weight'])] # wiersze gdzie niema braków w kolumnie 

size  color  gender  price  weight bought
3  NaN  green  female  129.0     NaN     no
5    M  green    male   89.0     NaN     no

In [34]:
df[~pd.isnull(df['weight'])] # przeciwieństwo poprzedniego

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue     NaN    NaN   300.0    yes
4    M    red  female   79.0   410.0    yes