In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print(torch.__version__)

2.2.0


## Tensory
### PyTorch tensors tworzysię przy pomocy torch.tensor() -> https://pytorch.org/docs/stable/tensors.html

In [3]:
# skalar, stworzenie tensora, jednoliczbowego
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
# wymiar tensora, tutaj zero ponieważ jest to jedna liczba - skalar
scalar.ndim

0

In [5]:
# odczyt wartości tensora, skalara
scalar.item()

7

In [6]:
# stworzenie tensora jednowymiarowego
vector = torch.tensor([7, 7, 2, 5])
vector

tensor([7, 7, 2, 5])

In [7]:
# jeden wymiar
vector.ndim

1

In [8]:
# odczyt wartości z pierwszego wymiaru która jest tesorem
vector[2]

tensor(2)

In [9]:
# odczyt wartości z pozycji
vector[3].item()

5

In [10]:
# kształt tensora, tablica jednowymiarowa czteroelementowa
vector.shape

torch.Size([4])

In [11]:
# dwa wymiary, matrix
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix, matrix.ndim, matrix.shape

(tensor([[ 7,  8],
         [ 9, 10]]),
 2,
 torch.Size([2, 2]))

In [12]:
# trzy wymiary, kształt jest liczony od części zewnętrznych
tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [5,6,7]]])
tensor, tensor.ndim, tensor.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [5, 6, 7]]]),
 3,
 torch.Size([1, 3, 3]))

## Random tensors
### https://pytorch.org/docs/stable/generated/torch.rand.html -> float
### https://pytorch.org/docs/stable/generated/torch.randint.html -> int
### https://pytorch.org/docs/stable/generated/torch.randn.html -> nominal dist

In [13]:
# generuje liczby pseudolosowe w tensorze o shape podanym w nawiasach
random_tensor = torch.rand(3, 4)
random_tensor, random_tensor.ndim, random_tensor.shape

(tensor([[0.2016, 0.6599, 0.6481, 0.6667],
         [0.7787, 0.2350, 0.2274, 0.8116],
         [0.8083, 0.5696, 0.3118, 0.1630]]),
 2,
 torch.Size([3, 4]))

## Tensors Zero and Ones

In [14]:
zeros = torch.zeros(4, 5)
zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [15]:
ones = torch.ones(2, 3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [16]:
# typ danych
zeros.dtype, ones.dtype

(torch.float32, torch.float32)

## Range of tensors and tensors-like
### https://pytorch.org/docs/stable/generated/torch.arange.html

In [17]:
# stworzenie jednowymiarowego tensora z zakresu liczb
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
co11 = torch.arange(start=0, end=100, step=11)
co11

tensor([ 0, 11, 22, 33, 44, 55, 66, 77, 88, 99])

In [19]:
# tworzenie tensora o takim samym shape ale wypełnionego zerami
torch.zeros_like(co11)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
# tosamo tylo z jedynkami
torch.ones_like(co11)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## Typy danych w tensorach
### https://pytorch.org/docs/stable/tensors.html

In [21]:
tFlot32 = torch.tensor([3., 6., 9.], dtype=None)  # None jest default, i oznacza rozpoznawanie automatyczna, liczba z kropką to float32 a bez int64
tFlot32, tFlot32.dtype

(tensor([3., 6., 9.]), torch.float32)

In [22]:
tFlot16 = torch.tensor([3., 5., 7.], dtype=torch.float16)
tFlot16, tFlot16.dtype

(tensor([3., 5., 7.], dtype=torch.float16), torch.float16)

In [23]:
tFlot64 = torch.tensor([3., 5., 7.], dtype=torch.float64)
tFlot64, tFlot64.dtype

(tensor([3., 5., 7.], dtype=torch.float64), torch.float64)

In [24]:
tInt = torch.tensor([3, 5, 7], dtype=None) # automatyczne rozpoznanie int64
tInt, tInt.dtype

(tensor([3, 5, 7]), torch.int64)

In [25]:
tInt = torch.tensor([3, 5, 7], dtype=torch.int16) 
tInt, tInt.dtype

(tensor([3, 5, 7], dtype=torch.int16), torch.int16)

In [26]:
tBool = torch.tensor([True, False, False], dtype=None) # automatyczne rozpoznanie typu bool
tBool, tBool.dtype

(tensor([ True, False, False]), torch.bool)

In [29]:
# ustawienia tensora
tFlot32 = torch.tensor([3., 6., 9.],
                       dtype=None, # typ danych
                       device=None, # CPU GPU ('None', 'cuda')
                       requires_grad=False, # śledzenie gradientem
                       pin_memory=False) # 
tFlot32, tFlot32.dtype

(tensor([3., 6., 9.]), torch.float32)

### Trzy główne błędy na typach danych w PyTorch
1. Tensor nie ma prawidłowego typu danych
2. Tensor nie ma prawidłowego shapa
3. Tensor nie jest uruchamiane na odpowiednim urządzeniu (CPU, GPU)

## Casting tensor 

In [32]:
cast_tF16 = tFlot64.type(torch.float16)
cast_tF16

tensor([3., 5., 7.], dtype=torch.float16)

## Atrybuty tensora

In [35]:
random_tensor = torch.rand(3, 4)
random_tensor, random_tensor.ndim, random_tensor.shape, random_tensor.size(), random_tensor.device, random_tensor.dtype

(tensor([[0.9686, 0.8669, 0.1920, 0.7122],
         [0.1769, 0.4344, 0.1812, 0.4491],
         [0.1351, 0.8644, 0.1291, 0.4628]]),
 2,
 torch.Size([3, 4]),
 torch.Size([3, 4]),
 device(type='cpu'),
 torch.float32)