1. Tensory
2. Random tensors
3. Tensors Zero and Ones
4. Range of tensors and tensors-like
5. Typy danych w tensorach
6. Trzy główne błędy na typach danych w PyTorch
7. Casting tensor
8. Atrybuty tensora
9. Operacje na tensorach
10. Matrix multiplication
11. Dwie podstawowe zasady przy 'Matrix mulltiplication'
12. Przewrócenie macierzy (transpose)
13. Wyszukiwanie min, max, obliczanie mean, sum, itd (tensor aggregation)
14. Wyszukiwanie indeksu nim, max
15. Reshaping, stacking, squeezing, unsqueezing -> przekształcanie, układanie, ściskanie, rozprężanie

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print(torch.__version__)

2.2.0


## 1. Tensory
### PyTorch tensors tworzysię przy pomocy torch.tensor() -> https://pytorch.org/docs/stable/tensors.html

In [3]:
# skalar, stworzenie tensora, jednoliczbowego
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
# wymiar tensora, tutaj zero ponieważ jest to jedna liczba - skalar
scalar.ndim

0

In [5]:
# odczyt wartości tensora, skalara
scalar.item()

7

In [6]:
# stworzenie tensora jednowymiarowego
vector = torch.tensor([7, 7, 2, 5])
vector

tensor([7, 7, 2, 5])

In [7]:
# jeden wymiar
vector.ndim

1

In [8]:
# odczyt wartości z pierwszego wymiaru która jest tesorem
vector[2]

tensor(2)

In [9]:
# odczyt wartości z pozycji
vector[3].item()

5

In [10]:
# kształt tensora, tablica jednowymiarowa czteroelementowa
vector.shape

torch.Size([4])

In [11]:
# dwa wymiary, matrix
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix, matrix.ndim, matrix.shape

(tensor([[ 7,  8],
         [ 9, 10]]),
 2,
 torch.Size([2, 2]))

In [12]:
# trzy wymiary, kształt jest liczony od części zewnętrznych
tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [5,6,7]]])
tensor, tensor.ndim, tensor.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [5, 6, 7]]]),
 3,
 torch.Size([1, 3, 3]))

## 2. Random tensors
### https://pytorch.org/docs/stable/generated/torch.rand.html -> float
### https://pytorch.org/docs/stable/generated/torch.randint.html -> int
### https://pytorch.org/docs/stable/generated/torch.randn.html -> nominal dist

In [13]:
# generuje liczby pseudolosowe w tensorze o shape podanym w nawiasach
random_tensor = torch.rand(3, 4)
random_tensor, random_tensor.ndim, random_tensor.shape

(tensor([[0.9585, 0.7172, 0.8645, 0.7023],
         [0.2978, 0.2107, 0.5506, 0.9033],
         [0.2041, 0.1084, 0.0086, 0.4466]]),
 2,
 torch.Size([3, 4]))

## 3. Tensors Zero and Ones

In [14]:
zeros = torch.zeros(4, 5)
zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [15]:
ones = torch.ones(2, 3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [16]:
# typ danych
zeros.dtype, ones.dtype

(torch.float32, torch.float32)

## 4. Range of tensors and tensors-like
### https://pytorch.org/docs/stable/generated/torch.arange.html

In [17]:
# stworzenie jednowymiarowego tensora z zakresu liczb
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
co11 = torch.arange(start=0, end=100, step=11)
co11

tensor([ 0, 11, 22, 33, 44, 55, 66, 77, 88, 99])

In [19]:
# tworzenie tensora o takim samym shape ale wypełnionego zerami
torch.zeros_like(co11)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
# tosamo tylo z jedynkami
torch.ones_like(co11)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## 5. Typy danych w tensorach
### https://pytorch.org/docs/stable/tensors.html

In [21]:
tFlot32 = torch.tensor([3., 6., 9.], dtype=None)  # None jest default, i oznacza rozpoznawanie automatyczna, liczba z kropką to float32 a bez int64
tFlot32, tFlot32.dtype

(tensor([3., 6., 9.]), torch.float32)

In [22]:
tFlot16 = torch.tensor([3., 5., 7.], dtype=torch.float16)
tFlot16, tFlot16.dtype

(tensor([3., 5., 7.], dtype=torch.float16), torch.float16)

In [23]:
tFlot64 = torch.tensor([3., 5., 7.], dtype=torch.float64)
tFlot64, tFlot64.dtype

(tensor([3., 5., 7.], dtype=torch.float64), torch.float64)

In [24]:
tInt = torch.tensor([3, 5, 7], dtype=None) # automatyczne rozpoznanie int64
tInt, tInt.dtype

(tensor([3, 5, 7]), torch.int64)

In [25]:
tInt = torch.tensor([3, 5, 7], dtype=torch.int16) 
tInt, tInt.dtype

(tensor([3, 5, 7], dtype=torch.int16), torch.int16)

In [26]:
tBool = torch.tensor([True, False, False], dtype=None) # automatyczne rozpoznanie typu bool
tBool, tBool.dtype

(tensor([ True, False, False]), torch.bool)

In [27]:
# ustawienia tensora
tFlot32 = torch.tensor([3., 6., 9.],
                       dtype=None, # typ danych
                       device=None, # CPU GPU ('None', 'cuda')
                       requires_grad=False, # śledzenie gradientem
                       pin_memory=False) # 
tFlot32, tFlot32.dtype

(tensor([3., 6., 9.]), torch.float32)

## 6. Trzy główne błędy na typach danych w PyTorch
1. Tensor nie ma prawidłowego typu danych
2. Tensor nie ma prawidłowego shapa
3. Tensor nie jest uruchamiane na odpowiednim urządzeniu (CPU, GPU)

## Casting tensor 

In [28]:
cast_tF16 = tFlot64.type(torch.float16)
cast_tF16

tensor([3., 5., 7.], dtype=torch.float16)

## Atrybuty tensora

In [29]:
random_tensor = torch.rand(3, 4)
random_tensor, random_tensor.ndim, random_tensor.shape, random_tensor.size(), random_tensor.device, random_tensor.dtype

(tensor([[0.1903, 0.2738, 0.8913, 0.1029],
         [0.9133, 0.1718, 0.7936, 0.0796],
         [0.5193, 0.0224, 0.5975, 0.1776]]),
 2,
 torch.Size([3, 4]),
 torch.Size([3, 4]),
 device(type='cpu'),
 torch.float32)

## Operacje na tensorach

### Operacje wbudowane:
* Addtion
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [30]:
tensor = torch.tensor([1, 2, 3])

#### Operacje zwykłym operatorem

In [31]:
tensor + 10

tensor([11, 12, 13])

In [32]:
tensor * 10

tensor([10, 20, 30])

In [33]:
tensor / 2

tensor([0.5000, 1.0000, 1.5000])

In [34]:
tensor - 11

tensor([-10,  -9,  -8])

#### Operacje wbudowane PyTorch

In [35]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [36]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [37]:
torch.sub(tensor, 30)

tensor([-29, -28, -27])

In [38]:
torch.div(tensor, 22)

tensor([0.0455, 0.0909, 0.1364])

### Matrix multiplication:


1. Element-wise miltiplication
2. Matrix multiplication (dot product)
* https://www.mathsisfun.com/algebra/matrix-multiplying.html
* http://matrixmultiplication.xyz/

In [39]:
# Element-wise miltiplication
print(tensor, "*", tensor, '=', tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])


In [40]:
print(tensor, "* 10 =", tensor * 10)

tensor([1, 2, 3]) * 10 = tensor([10, 20, 30])


In [41]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [42]:
tensor 

tensor([1, 2, 3])

In [43]:
# Obliczenie ręczne
1*1 + 2*2 + 3*3

14

In [44]:
tensor = torch.arange(0, 10000)
tensor = tensor / 3.333
tensor[:18]

tensor([0.0000, 0.3000, 0.6001, 0.9001, 1.2001, 1.5002, 1.8002, 2.1002, 2.4002,
        2.7003, 3.0003, 3.3003, 3.6004, 3.9004, 4.2004, 4.5005, 4.8005, 5.1005])

In [45]:
%%time
value = 0 
for i in range(len(tensor)):
   value += tensor[i] * tensor[i]
value

CPU times: total: 93.8 ms
Wall time: 115 ms


tensor(3.0001e+10)

In [46]:
%%time
value = 0 
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 1 ms


tensor(3.0002e+10)

## Dwie podstawowe zasady przy 'Matrix mulltiplication' które muszą być zachowane:
1. Wewnętrzne rozmiary maciezy muszą być takie same:
* (3, 2) @ (3, 2) -> nie zadziała (tensor @ tensor to tosamo co torch.matmul(tensor, tensor))
* (3, 2) @ (2, 3) -> zadziała
* (2, 3) @ (3, 2) -> zadziała


### 2. W wyniku 'Matrix mulltiplication' macierz ma wymiary takie same jak zewnętrzne wymiary macierzy do mnożenia
* (3, 2) @ (2, 3) -> (3, 3)
* (2, 3) @ (3, 2) -> (2, 2)

In [47]:
# torch.matmul(torch.rand(3, 2), torch.rand(3, 2)) # tu będzie błąd

In [48]:
out = torch.matmul(torch.rand(3, 2), torch.rand(2, 3))
out, out.shape

(tensor([[0.0453, 0.1528, 0.0946],
         [0.0678, 0.1860, 0.1255],
         [0.0102, 0.0628, 0.0319]]),
 torch.Size([3, 3]))

In [49]:
out = torch.matmul(torch.rand(2, 3), torch.rand(3, 2))
out, out.shape

(tensor([[0.4021, 0.6853],
         [0.7549, 1.2755]]),
 torch.Size([2, 2]))

In [50]:
# te same operacjem, różne zapisy
t1 = torch.rand(3, 2) 
t2 = torch.rand(2, 3)

t1 @ t2, torch.matmul(t1, t2), torch.mm(t1, t2)

(tensor([[0.3815, 1.0362, 0.3395],
         [0.2662, 0.5183, 0.1219],
         [0.2353, 0.9517, 0.3851]]),
 tensor([[0.3815, 1.0362, 0.3395],
         [0.2662, 0.5183, 0.1219],
         [0.2353, 0.9517, 0.3851]]),
 tensor([[0.3815, 1.0362, 0.3395],
         [0.2662, 0.5183, 0.1219],
         [0.2353, 0.9517, 0.3851]]))

In [51]:
t1 = torch.rand(3, 2) 
t2 = torch.rand(3, 2)
t1, t2, t1.shape, t2.shape

(tensor([[0.7118, 0.9041],
         [0.2665, 0.7221],
         [0.1939, 0.0507]]),
 tensor([[0.3558, 0.6105],
         [0.8969, 0.1314],
         [0.9491, 0.7085]]),
 torch.Size([3, 2]),
 torch.Size([3, 2]))

## Przewrócenie macierzy (transpose)

In [52]:
# torch.matmul(t1, t2) # bedzie błąd bo są złe shapy, ale można użyć funkcji transpose żeby odwrócić jedną z macierzy

In [53]:
t2, t2.shape, t2.T, t2.T.shape

(tensor([[0.3558, 0.6105],
         [0.8969, 0.1314],
         [0.9491, 0.7085]]),
 torch.Size([3, 2]),
 tensor([[0.3558, 0.8969, 0.9491],
         [0.6105, 0.1314, 0.7085]]),
 torch.Size([2, 3]))

In [54]:
torch.matmul(t1, t2.T) # i teraz jest dobrze

tensor([[0.8052, 0.7572, 1.3162],
        [0.5357, 0.3339, 0.7646],
        [0.0999, 0.1806, 0.2199]])

## Wyszukiwanie min, max, obliczanie mean, sum, itd (tensor aggregation)

In [74]:
X = torch.randint(100, size=(10,))
X

tensor([47, 35, 75, 69, 89, 90, 39,  1,  4, 79])

In [75]:
torch.min(X), X.min() # aliasy min

(tensor(1), tensor(1))

In [76]:
torch.max(X), X.max()

(tensor(90), tensor(90))

In [77]:
torch.mean(X.type(torch.float32)) # trzeba zamienić na float bo na int64 mean nie działa i bedzie error

tensor(52.8000)

In [78]:
X.type(torch.float32).mean() # alias tego co wyżej

tensor(52.8000)

In [79]:
torch.sum(X), X.sum()

(tensor(528), tensor(528))

## Wyszukiwanie indeksu nim, max

In [80]:
X

tensor([47, 35, 75, 69, 89, 90, 39,  1,  4, 79])

In [84]:
X.argmin(), X[X.argmin()].item()

(tensor(7), 1)

In [85]:
X.argmax(), X[X.argmax()].item()

(tensor(5), 90)

## Reshaping, stacking, squeezing, unsqueezing -> przekształcanie, układanie, ściskanie, rozprężanie