1. Tensory
2. Random tensors
3. Tensors Zero and Ones
4. Range of tensors and tensors-like
5. Typy danych w tensorach
6. Trzy główne błędy na typach danych w PyTorch
7. Casting tensor
8. Atrybuty tensora
9. Operacje na tensorach
10. Matrix multiplication
11. Dwie podstawowe zasady przy 'Matrix mulltiplication'
12. Przewrócenie macierzy (transpose)
13. Wyszukiwanie min, max, obliczanie mean, sum, itd (tensor aggregation)
14. Wyszukiwanie indeksu nim, max
15. Reshaping and view -> zmiana kształtu
16. Stacking -> łączenie tensorów
17. Squeezing -> usunięcie wymiarów '1' z tensora
18. Unsqueezing -> dodanie wymiaru '1' do tensora
19. Permute -> przestawienie kolejności
20. Zmiana wartości w tensorach, indexowanie
21. PyTorch an NumPy
22. Odtwarzalność random -> ten sam start liczb losowych
23. CPU GPU ('cpu', 'cuda')

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.2.0


## 1. Tensory

### PyTorch tensors tworzysię przy pomocy torch.tensor()
Trzy główne błędy na typach danych w PyTorch

In [2]:
# skalar, stworzenie tensora, jednoliczbowego
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# wymiar tensora, tutaj zero ponieważ jest to jedna liczba - skalar
scalar.ndim

0

In [4]:
# odczyt wartości tensora, skalara
scalar.item()

7

In [5]:
# stworzenie tensora jednowymiarowego
vector = torch.tensor([7, 7, 2, 5])
vector

tensor([7, 7, 2, 5])

In [6]:
# jeden wymiar
vector.ndim

1

In [7]:
# odczyt wartości z pierwszego wymiaru która jest tesorem
vector[2]

tensor(2)

In [8]:
# odczyt wartości z pozycji
vector[3].item()

5

In [9]:
# kształt tensora, tablica jednowymiarowa czteroelementowa
vector.shape

torch.Size([4])

In [10]:
# dwa wymiary, matrix
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix, matrix.ndim, matrix.shape

(tensor([[ 7,  8],
         [ 9, 10]]),
 2,
 torch.Size([2, 2]))

In [11]:
# trzy wymiary, kształt jest liczony od części zewnętrznych
tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [5,6,7]]])
tensor, tensor.ndim, tensor.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [5, 6, 7]]]),
 3,
 torch.Size([1, 3, 3]))

## 2. Random tensors

### https://pytorch.org/docs/stable/generated/torch.rand.html -> float
### https://pytorch.org/docs/stable/generated/torch.randint.html -> int
### https://pytorch.org/docs/stable/generated/torch.randn.html -> nominal dist

In [12]:
# generuje liczby pseudolosowe w tensorze o shape podanym w nawiasach
random_tensor = torch.rand(3, 4)
random_tensor, random_tensor.ndim, random_tensor.shape

(tensor([[0.8321, 0.0857, 0.1559, 0.9855],
         [0.8646, 0.9803, 0.6421, 0.0798],
         [0.2916, 0.5152, 0.9268, 0.3362]]),
 2,
 torch.Size([3, 4]))

## 3. Tensors Zero and Ones

In [13]:
zeros = torch.zeros(4, 5)
zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [14]:
ones = torch.ones(2, 3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [15]:
# typ danych
zeros.dtype, ones.dtype

(torch.float32, torch.float32)

## 4. Range of tensors and tensors-like

### https://pytorch.org/docs/stable/generated/torch.arange.html

In [16]:
# stworzenie jednowymiarowego tensora z zakresu liczb
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
co11 = torch.arange(start=0, end=100, step=11)
co11

tensor([ 0, 11, 22, 33, 44, 55, 66, 77, 88, 99])

In [18]:
# tworzenie tensora o takim samym shape ale wypełnionego zerami
torch.zeros_like(co11)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
# tosamo tylo z jedynkami
torch.ones_like(co11)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## 5. Typy danych w tensorach

### https://pytorch.org/docs/stable/tensors.html

In [20]:
tFlot32 = torch.tensor([3., 6., 9.], dtype=None)  # None jest default, i oznacza rozpoznawanie automatyczna, liczba z kropką to float32 a bez int64
tFlot32, tFlot32.dtype

(tensor([3., 6., 9.]), torch.float32)

In [21]:
tFlot16 = torch.tensor([3., 5., 7.], dtype=torch.float16)
tFlot16, tFlot16.dtype

(tensor([3., 5., 7.], dtype=torch.float16), torch.float16)

In [22]:
tFlot64 = torch.tensor([3., 5., 7.], dtype=torch.float64)
tFlot64, tFlot64.dtype

(tensor([3., 5., 7.], dtype=torch.float64), torch.float64)

In [23]:
tInt = torch.tensor([3, 5, 7], dtype=None) # automatyczne rozpoznanie int64
tInt, tInt.dtype

(tensor([3, 5, 7]), torch.int64)

In [24]:
tInt = torch.tensor([3, 5, 7], dtype=torch.int16) 
tInt, tInt.dtype

(tensor([3, 5, 7], dtype=torch.int16), torch.int16)

In [25]:
tBool = torch.tensor([True, False, False], dtype=None) # automatyczne rozpoznanie typu bool
tBool, tBool.dtype

(tensor([ True, False, False]), torch.bool)

In [26]:
# ustawienia tensora
tFlot32 = torch.tensor([3., 6., 9.],
                       dtype=None, # typ danych
                       device=None, # CPU GPU ('None', 'cuda')
                       requires_grad=False, # śledzenie gradientem
                       pin_memory=False) # 
tFlot32, tFlot32.dtype

(tensor([3., 6., 9.]), torch.float32)

## 6. Trzy główne błędy na typach danych w PyTorch

1. Tensor nie ma prawidłowego typu danych
2. Tensor nie ma prawidłowego shapa
3. Tensor nie jest uruchamiane na odpowiednim urządzeniu (CPU, GPU)

## 7. Casting tensor 

In [27]:
cast_tF16 = tFlot64.type(torch.float16)
cast_tF16

tensor([3., 5., 7.], dtype=torch.float16)

## 8. Atrybuty tensora

In [28]:
random_tensor = torch.rand(3, 4)
random_tensor, random_tensor.ndim, random_tensor.shape, random_tensor.size(), random_tensor.device, random_tensor.dtype

(tensor([[0.2631, 0.1796, 0.8650, 0.3573],
         [0.3485, 0.7514, 0.8415, 0.3270],
         [0.5999, 0.5981, 0.1328, 0.9274]]),
 2,
 torch.Size([3, 4]),
 torch.Size([3, 4]),
 device(type='cpu'),
 torch.float32)

## 9. Operacje na tensorach

### Operacje wbudowane:
* Addtion
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [29]:
tensor = torch.tensor([1, 2, 3])

#### Operacje zwykłym operatorem

In [30]:
tensor + 10

tensor([11, 12, 13])

In [31]:
tensor * 10

tensor([10, 20, 30])

In [32]:
tensor / 2

tensor([0.5000, 1.0000, 1.5000])

In [33]:
tensor - 11

tensor([-10,  -9,  -8])

#### Operacje wbudowane PyTorch

In [34]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [35]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [36]:
torch.sub(tensor, 30)

tensor([-29, -28, -27])

In [37]:
torch.div(tensor, 22)

tensor([0.0455, 0.0909, 0.1364])

## 10. Matrix multiplication


1. Element-wise miltiplication
2. Matrix multiplication (dot product)
* https://www.mathsisfun.com/algebra/matrix-multiplying.html
* http://matrixmultiplication.xyz/

In [38]:
# Element-wise miltiplication
print(tensor, "*", tensor, '=', tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])


In [39]:
print(tensor, "* 10 =", tensor * 10)

tensor([1, 2, 3]) * 10 = tensor([10, 20, 30])


In [40]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [41]:
tensor 

tensor([1, 2, 3])

In [42]:
# Obliczenie ręczne
1*1 + 2*2 + 3*3

14

In [43]:
tensor = torch.arange(0, 10000)
tensor = tensor / 3.333
tensor[:18]

tensor([0.0000, 0.3000, 0.6001, 0.9001, 1.2001, 1.5002, 1.8002, 2.1002, 2.4002,
        2.7003, 3.0003, 3.3003, 3.6004, 3.9004, 4.2004, 4.5005, 4.8005, 5.1005])

In [44]:
%%time
value = 0 
for i in range(len(tensor)):
   value += tensor[i] * tensor[i]
value

CPU times: total: 78.1 ms
Wall time: 99.6 ms


tensor(3.0001e+10)

In [45]:
%%time
value = 0 
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 1.26 ms


tensor(3.0002e+10)

## 11. Dwie podstawowe zasady przy 'Matrix mulltiplication' które muszą być zachowane

1. Wewnętrzne rozmiary maciezy muszą być takie same:
* (3, 2) @ (3, 2) -> nie zadziała (tensor @ tensor to tosamo co torch.matmul(tensor, tensor))
* (3, 2) @ (2, 3) -> zadziała
* (2, 3) @ (3, 2) -> zadziała

2. W wyniku 'Matrix mulltiplication' macierz ma wymiary takie same jak zewnętrzne wymiary macierzy do mnożenia
* (3, 2) @ (2, 3) -> (3, 3)
* (2, 3) @ (3, 2) -> (2, 2)

In [46]:
# torch.matmul(torch.rand(3, 2), torch.rand(3, 2)) # tu będzie błąd

In [47]:
out = torch.matmul(torch.rand(3, 2), torch.rand(2, 3))
out, out.shape

(tensor([[0.8033, 0.6203, 0.2062],
         [0.0459, 0.0399, 0.0115],
         [1.0211, 0.7263, 0.2666]]),
 torch.Size([3, 3]))

In [48]:
out = torch.matmul(torch.rand(2, 3), torch.rand(3, 2))
out, out.shape

(tensor([[0.8128, 0.3593],
         [0.9439, 0.4080]]),
 torch.Size([2, 2]))

In [49]:
# te same operacjem, różne zapisy
t1 = torch.rand(3, 2) 
t2 = torch.rand(2, 3)

t1 @ t2, torch.matmul(t1, t2), torch.mm(t1, t2)

(tensor([[0.7000, 0.6690, 0.8869],
         [0.4663, 0.4632, 0.5155],
         [1.0248, 1.0306, 1.0789]]),
 tensor([[0.7000, 0.6690, 0.8869],
         [0.4663, 0.4632, 0.5155],
         [1.0248, 1.0306, 1.0789]]),
 tensor([[0.7000, 0.6690, 0.8869],
         [0.4663, 0.4632, 0.5155],
         [1.0248, 1.0306, 1.0789]]))

In [50]:
t1 = torch.rand(3, 2) 
t2 = torch.rand(3, 2)
t1, t2, t1.shape, t2.shape

(tensor([[0.9726, 0.8059],
         [0.0126, 0.7894],
         [0.8490, 0.0831]]),
 tensor([[0.7605, 0.8409],
         [0.0608, 0.9038],
         [0.5984, 0.7106]]),
 torch.Size([3, 2]),
 torch.Size([3, 2]))

## 12. Przewrócenie macierzy (transpose)

In [51]:
# torch.matmul(t1, t2) # bedzie błąd bo są złe shapy, ale można użyć funkcji transpose żeby odwrócić jedną z macierzy

In [52]:
t2, t2.shape, t2.T, t2.T.shape

(tensor([[0.7605, 0.8409],
         [0.0608, 0.9038],
         [0.5984, 0.7106]]),
 torch.Size([3, 2]),
 tensor([[0.7605, 0.0608, 0.5984],
         [0.8409, 0.9038, 0.7106]]),
 torch.Size([2, 3]))

In [53]:
torch.matmul(t1, t2.T) # i teraz jest dobrze

tensor([[1.4174, 0.7876, 1.1547],
        [0.6734, 0.7142, 0.5684],
        [0.7156, 0.1268, 0.5671]])

## 13. Wyszukiwanie min, max, obliczanie mean, sum, itd (tensor aggregation)

In [54]:
X = torch.randint(100, size=(10,))
X

tensor([26, 16, 27, 95,  6, 13, 15, 33, 18, 71])

In [55]:
torch.min(X), X.min() # aliasy min

(tensor(6), tensor(6))

In [56]:
torch.max(X), X.max()

(tensor(95), tensor(95))

In [57]:
torch.mean(X.type(torch.float32)) # trzeba zamienić na float bo na int64 mean nie działa i bedzie error

tensor(32.)

In [58]:
X.type(torch.float32).mean() # alias tego co wyżej

tensor(32.)

In [59]:
torch.sum(X), X.sum()

(tensor(320), tensor(320))

## 14. Wyszukiwanie indeksu nim, max

In [60]:
X

tensor([26, 16, 27, 95,  6, 13, 15, 33, 18, 71])

In [61]:
X.argmin(), X[X.argmin()].item()

(tensor(4), 6)

In [62]:
X.argmax(), X[X.argmax()].item()

(tensor(3), 95)

## 15. Reshaping and view

#### Reshaping

In [63]:
X = torch.arange(1., 10.)
X, X.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [64]:
# reshape to zmiana kształu tensora ale ilość danych musi się zgadzać
X_reshape = X.reshape(3, 3)
X_reshape, X_reshape.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [65]:
X_reshape = X.reshape(9, 1)
X_reshape, X_reshape.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [66]:
X_reshape = X.reshape(1, 9)
X_reshape, X_reshape.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

#### View

In [67]:
# view - funkcjonuje tak samo jak reshape, ale działa na tej samej pamięci, 
# więc jak się stworzy alias i się go zmieni to zmieni się też oryginał, nie chodzi o kształt tylko o dane
X, X.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [68]:
Z = X.view(3, 3)
X.shape, Z.shape

(torch.Size([9]), torch.Size([3, 3]))

In [69]:
X, Z

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]))

In [70]:
Z[1,1] = 11
Z, X

(tensor([[ 1.,  2.,  3.],
         [ 4., 11.,  6.],
         [ 7.,  8.,  9.]]),
 tensor([ 1.,  2.,  3.,  4., 11.,  6.,  7.,  8.,  9.]))

## 16. Stacking

In [71]:
# Staking to łączenie tensorów
X

tensor([ 1.,  2.,  3.,  4., 11.,  6.,  7.,  8.,  9.])

In [72]:
X_stack = torch.stack([X, X, X, X], dim=0)
X_stack, X_stack.shape

(tensor([[ 1.,  2.,  3.,  4., 11.,  6.,  7.,  8.,  9.],
         [ 1.,  2.,  3.,  4., 11.,  6.,  7.,  8.,  9.],
         [ 1.,  2.,  3.,  4., 11.,  6.,  7.,  8.,  9.],
         [ 1.,  2.,  3.,  4., 11.,  6.,  7.,  8.,  9.]]),
 torch.Size([4, 9]))

In [73]:
X_stack = torch.stack([X, X, X, X], dim=1)
X_stack, X_stack.shape

(tensor([[ 1.,  1.,  1.,  1.],
         [ 2.,  2.,  2.,  2.],
         [ 3.,  3.,  3.,  3.],
         [ 4.,  4.,  4.,  4.],
         [11., 11., 11., 11.],
         [ 6.,  6.,  6.,  6.],
         [ 7.,  7.,  7.,  7.],
         [ 8.,  8.,  8.,  8.],
         [ 9.,  9.,  9.,  9.]]),
 torch.Size([9, 4]))

In [74]:
X_stack = torch.vstack([X, X, X, X])
X_stack, X_stack.shape

(tensor([[ 1.,  2.,  3.,  4., 11.,  6.,  7.,  8.,  9.],
         [ 1.,  2.,  3.,  4., 11.,  6.,  7.,  8.,  9.],
         [ 1.,  2.,  3.,  4., 11.,  6.,  7.,  8.,  9.],
         [ 1.,  2.,  3.,  4., 11.,  6.,  7.,  8.,  9.]]),
 torch.Size([4, 9]))

In [75]:
X_stack = torch.hstack([X, X, X, X])
X_stack, X_stack.shape

(tensor([ 1.,  2.,  3.,  4., 11.,  6.,  7.,  8.,  9.,  1.,  2.,  3.,  4., 11.,
          6.,  7.,  8.,  9.,  1.,  2.,  3.,  4., 11.,  6.,  7.,  8.,  9.,  1.,
          2.,  3.,  4., 11.,  6.,  7.,  8.,  9.]),
 torch.Size([36]))

## 17. Squeezing - usunięcie wymiarów '1' z tensora

In [76]:
X = torch.rand(size=(3, 3, 1))
X, X.shape

(tensor([[[0.2674],
          [0.9314],
          [0.6231]],
 
         [[0.8709],
          [0.3031],
          [0.9246]],
 
         [[0.1266],
          [0.4881],
          [0.5896]]]),
 torch.Size([3, 3, 1]))

In [77]:
X_squeez = X.squeeze()
X_squeez, X_squeez.shape

(tensor([[0.2674, 0.9314, 0.6231],
         [0.8709, 0.3031, 0.9246],
         [0.1266, 0.4881, 0.5896]]),
 torch.Size([3, 3]))

## 18. Unsqueezing - dodanie wymiaru '1' do tensora

In [78]:
X = torch.rand(size=(3, 3))
X, X.shape

(tensor([[0.6614, 0.5941, 0.9720],
         [0.1177, 0.7152, 0.1083],
         [0.5708, 0.9637, 0.8679]]),
 torch.Size([3, 3]))

In [79]:
X_unsqueez = X.unsqueeze(dim=0)
X_unsqueez, X_unsqueez.shape

(tensor([[[0.6614, 0.5941, 0.9720],
          [0.1177, 0.7152, 0.1083],
          [0.5708, 0.9637, 0.8679]]]),
 torch.Size([1, 3, 3]))

In [80]:
X_unsqueez = X.unsqueeze(dim=1)
X_unsqueez, X_unsqueez.shape

(tensor([[[0.6614, 0.5941, 0.9720]],
 
         [[0.1177, 0.7152, 0.1083]],
 
         [[0.5708, 0.9637, 0.8679]]]),
 torch.Size([3, 1, 3]))

In [81]:
X_unsqueez = X.unsqueeze(dim=2)
X_unsqueez, X_unsqueez.shape

(tensor([[[0.6614],
          [0.5941],
          [0.9720]],
 
         [[0.1177],
          [0.7152],
          [0.1083]],
 
         [[0.5708],
          [0.9637],
          [0.8679]]]),
 torch.Size([3, 3, 1]))

## 19. Permute -> przestawienie kolejności wymiarów

In [82]:
X = torch.rand(size=(3, 4, 2))
X, X.shape

(tensor([[[0.9322, 0.2479],
          [0.3739, 0.9390],
          [0.9610, 0.1560],
          [0.0562, 0.6035]],
 
         [[0.9236, 0.6642],
          [0.7879, 0.5503],
          [0.1530, 0.3324],
          [0.6281, 0.8341]],
 
         [[0.0569, 0.8939],
          [0.8763, 0.4736],
          [0.0409, 0.5765],
          [0.7729, 0.3896]]]),
 torch.Size([3, 4, 2]))

In [83]:
X_permute = X.permute(2, 0, 1) # w nawiasie są indexy wymiarów, czyli 0->3, 1->4, 2->2
X_permute, X_permute.shape

(tensor([[[0.9322, 0.3739, 0.9610, 0.0562],
          [0.9236, 0.7879, 0.1530, 0.6281],
          [0.0569, 0.8763, 0.0409, 0.7729]],
 
         [[0.2479, 0.9390, 0.1560, 0.6035],
          [0.6642, 0.5503, 0.3324, 0.8341],
          [0.8939, 0.4736, 0.5765, 0.3896]]]),
 torch.Size([2, 3, 4]))

## 20. Zmiana wartości w tensorach, indexowanie

In [110]:
X = torch.arange(1, 19).reshape(2, 3, 3)
X, X.shape
# tensor jest trój wymiarowy

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],
 
         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]]]),
 torch.Size([2, 3, 3]))

In [111]:
X[0] # wyświetlany jest tensor dwu wymiarowy 2 i 3 wymiaru

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [112]:
X[0, 0] # wyświetlany jest tensor jednowymiarowy 3 wymiaru
# X[0][0]

tensor([1, 2, 3])

In [113]:
X[0, 0, 0] # wyświetlany jest skalar
# X[0][0][0]

tensor(1)

In [114]:
X[0, 0, 0].item() # wyświetlana jest sama wartość
# X[0][0][0].item()

1

In [115]:
# X[0, 0, 0] = 100 # przypisanie wartości
X

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

In [121]:
X[:, 0] # ':' zastępuje wszystkie pierwsze wymiary, czyli wyświetl wszystkie 3-cie wymiary zerowego wiersza

tensor([[ 1,  2,  3],
        [10, 11, 12]])

In [122]:
X[:, 1] # wyświetl wszystkie 3-cie wymiary pierwszego wiersza

tensor([[ 4,  5,  6],
        [13, 14, 15]])

In [126]:
X[:, :, 0] # wszystkie 0-we wymiary, wszystkie 1-wsze wymiary (wiersze), 0-we kolumny

tensor([[ 1,  4,  7],
        [10, 13, 16]])

In [127]:
X[:, 1, 1] # wystkie 0-we wymiary, 1-wszy wiersz, 1-wsza kolumna

tensor([ 5, 14])

In [129]:
X[0, 0, :] 

tensor([1, 2, 3])

In [131]:
X[0, :, 2]

tensor([3, 6, 9])

In [132]:
X[0, 2, 2]

tensor(9)

## 21. PyTorch an NumPy

#### NumPy array to tensor

In [161]:
array = np.arange(1.0, 8.0)
tensorFromNumPy = torch.from_numpy(array)
array, tensorFromNumPy

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [162]:
# jeszcze trzeba zmienić typ na domyślny w tensor
tensorFromNumPy = tensorFromNumPy.type(torch.float32)
tensorFromNumPy, tensorFromNumPy.dtype

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.float32)

In [163]:
# można to zrobić za jednym zamachem
array = np.arange(1.0, 8.0)
tensorFromNumPy = torch.from_numpy(array).type(torch.float32)
array, tensorFromNumPy

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [165]:
tensorFromNumPy[0] = 111
array, tensorFromNumPy

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([111.,   2.,   3.,   4.,   5.,   6.,   7.]))

##### UWAGA: jak zmieniemy dane w tensor to niezmienią się w array

#### Tensor to NumPy array

In [176]:
tensor = torch.ones(7)
arrayFromTensor = tensor.numpy()
tensor, arrayFromTensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [179]:
arrayFromTensor[0] = 111
tensor, arrayFromTensor

(tensor([111.,   1.,   1.,   1.,   1.,   1.,   1.]),
 array([111.,   1.,   1.,   1.,   1.,   1.,   1.], dtype=float32))

In [180]:
tensor[0] = 222
tensor, arrayFromTensor

(tensor([222.,   1.,   1.,   1.,   1.,   1.,   1.]),
 array([222.,   1.,   1.,   1.,   1.,   1.,   1.], dtype=float32))

##### UWAGA: jak zmieniemy dane w array to zmienią się też w tensor

## 22. Odtwarzalność random -> ten sam start liczb losowych

In [191]:
torch.manual_seed(42) # liczby pseudo losowe startują od tejsamej wartości

X = torch.rand(2, 3)
X

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

## 23. CPU GPU ('cpu', 'cuda')

In [202]:
# https://pytorch.org/docs/stable/notes/cuda.html#best-practices
!nvidia-smi

Fri Feb 23 22:53:38 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 546.65                 Driver Version: 546.65       CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1650      WDDM  | 00000000:0B:00.0  On |                  N/A |
|  0%   47C    P8              N/A /  75W |    864MiB /  4096MiB |      1%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [194]:
torch.cuda.is_available()

True

In [200]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [201]:
torch.cuda.device_count()

1

### Przełączenie tensora na GPU

In [203]:
tensor = torch.tensor([1, 2, 3])
tensor.device

device(type='cpu')

In [204]:
tensorGPU = tensor.to(device)
tensorGPU.device

device(type='cuda', index=0)

### Z powrotem do CPU

In [208]:
tensorGPU.cpu().numpy()

array([1, 2, 3], dtype=int64)